<a href="https://colab.research.google.com/github/sjrover007/LearningDeep/blob/main/Lab5_Predicting_next_element_in_sequence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code implements RNN to learn a simple sequence and predict the next element in the sequence , input seq.[2,4,6,8,10],y=12

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [32]:
#Generate some sample data
x = np.array([[2*(i+j) for j in range(6)] for i in range(100)])
y = np.array([2*i+12 for i in range(100)])

x,y

(array([[  0,   2,   4,   6,   8,  10],
        [  2,   4,   6,   8,  10,  12],
        [  4,   6,   8,  10,  12,  14],
        [  6,   8,  10,  12,  14,  16],
        [  8,  10,  12,  14,  16,  18],
        [ 10,  12,  14,  16,  18,  20],
        [ 12,  14,  16,  18,  20,  22],
        [ 14,  16,  18,  20,  22,  24],
        [ 16,  18,  20,  22,  24,  26],
        [ 18,  20,  22,  24,  26,  28],
        [ 20,  22,  24,  26,  28,  30],
        [ 22,  24,  26,  28,  30,  32],
        [ 24,  26,  28,  30,  32,  34],
        [ 26,  28,  30,  32,  34,  36],
        [ 28,  30,  32,  34,  36,  38],
        [ 30,  32,  34,  36,  38,  40],
        [ 32,  34,  36,  38,  40,  42],
        [ 34,  36,  38,  40,  42,  44],
        [ 36,  38,  40,  42,  44,  46],
        [ 38,  40,  42,  44,  46,  48],
        [ 40,  42,  44,  46,  48,  50],
        [ 42,  44,  46,  48,  50,  52],
        [ 44,  46,  48,  50,  52,  54],
        [ 46,  48,  50,  52,  54,  56],
        [ 48,  50,  52,  54,  56,  58],


In [33]:
# Reshape the data for RNN input
x = x.reshape(x.shape[0], x.shape[1], 1)
x.shape

(100, 6, 1)

In [34]:
#Define the RNN model
model = Sequential([SimpleRNN(
    units=128,
    input_shape=(x.shape[1], x.shape[2]),
    activation= 'relu'
    ),
    Dense(1)])

In [35]:
#compile the model
model.compile(optimizer='adam', loss='mse')

In [36]:
#Train the model
model.fit(x, y, epochs=20, batch_size=10)

Epoch 1/20
10/10 [==============================] - 1s 5ms/step - loss: 8663.0752
Epoch 2/20
10/10 [==============================] - 0s 5ms/step - loss: 653.5505
Epoch 3/20
10/10 [==============================] - 0s 6ms/step - loss: 320.9008
Epoch 4/20
10/10 [==============================] - 0s 5ms/step - loss: 170.1004
Epoch 5/20
10/10 [==============================] - 0s 6ms/step - loss: 30.1298
Epoch 6/20
10/10 [==============================] - 0s 5ms/step - loss: 15.9408
Epoch 7/20
10/10 [==============================] - 0s 8ms/step - loss: 10.5650
Epoch 8/20
10/10 [==============================] - 0s 8ms/step - loss: 7.4707
Epoch 9/20
10/10 [==============================] - 0s 10ms/step - loss: 6.3053
Epoch 10/20
10/10 [==============================] - 0s 7ms/step - loss: 5.3213
Epoch 11/20
10/10 [==============================] - 0s 6ms/step - loss: 4.7574
Epoch 12/20
10/10 [==============================] - 0s 6ms/step - loss: 4.7527
Epoch 13/20
10/10 [=================

In [37]:
#Test the model
test_input = np.array([[2*(i+j) for j in range(6)] for i in range(100,120)])
test_input = test_input.reshape(test_input.shape[0], test_input.shape[1], 1)
predicted_output = model.predict(test_input)

1/1 [==============================] - 0s 274ms/step


In [38]:
#Print the predicted output
print("Predicted Output:")
print(predicted_output.flatten())

Predicted Output:
[214.77946 216.84785 218.91621 220.98457 223.05298 225.12134 227.18971
 229.2581  231.32649 233.39484 235.46323 237.5316  239.59998 241.66835
 243.73671 245.8051  247.87349 249.94185 252.01025 254.07861]


**ALPHABET prediction model using RNN**

In [63]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [64]:
#Generate some sample data
alphabet = "abcdefghijklmnopqrstuvwxyz"
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

#char_to_int,int_to_char

In [65]:
data = []
for i in range(len(alphabet) - 1):
  data.append([char_to_int[alphabet[i]], char_to_int[alphabet[i+1]]])
x = np.array(data)
y = np.array(data)[:,1]
x,y

(array([[ 0,  1],
        [ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 4,  5],
        [ 5,  6],
        [ 6,  7],
        [ 7,  8],
        [ 8,  9],
        [ 9, 10],
        [10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22],
        [22, 23],
        [23, 24],
        [24, 25]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25]))

In [66]:
# Reshape the data for RNN input
x = x.reshape(x.shape[0], x.shape[1], 1)
x.shape

(25, 2, 1)

In [71]:
#Define the RNN model
model = Sequential([
    SimpleRNN(
    units=128,
    input_shape=(x.shape[1], x.shape[2]),
    activation= 'softmax'
    ),
    Dense(len(alphabet))])

In [77]:
#compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

In [73]:

#Train the model
model.fit(x, y, epochs=10, batch_size=8)

Epoch 1/10
4/4 [==============================] - 1s 7ms/step - loss: 10.3267
Epoch 2/10
4/4 [==============================] - 0s 5ms/step - loss: 9.8687
Epoch 3/10
4/4 [==============================] - 0s 5ms/step - loss: 9.2537
Epoch 4/10
4/4 [==============================] - 0s 5ms/step - loss: 7.2917
Epoch 5/10
4/4 [==============================] - 0s 5ms/step - loss: 6.4703
Epoch 6/10
4/4 [==============================] - 0s 5ms/step - loss: 6.4360
Epoch 7/10
4/4 [==============================] - 0s 7ms/step - loss: 5.5266
Epoch 8/10
4/4 [==============================] - 0s 5ms/step - loss: 4.4439
Epoch 9/10
4/4 [==============================] - 0s 6ms/step - loss: 3.2581
Epoch 10/10
4/4 [==============================] - 0s 6ms/step - loss: 3.2581


In [76]:
#modify model to accept current shape of test data
model = Sequential([
    SimpleRNN(
    units=128,
    input_shape=(test_input.shape[1], test_input.shape[2]),
    activation= 'softmax'
    ),
    Dense(len(alphabet))])

In [78]:
#Test the model
test_input = np.array([[char_to_int[alphabet[i]]] for i in range(10,25)])
test_input = test_input.reshape(test_input.shape[0], test_input.shape[1], 1)

# Reshape the test data to match the expected input shape
test_input = np.expand_dims(test_input, axis=1)
#test_input
predicted_output = model.predict(test_input)

1/1 [==============================] - 0s 286ms/step


In [79]:
#Print the predicted output
print("Predicted Output:")
for i in range(len(predicted_output)):
  predicted_char = int_to_char[np.argmax(predicted_output[i])]
  print(predicted_char)

Predicted Output:
n
n
n
n
n
n
n
n
n
n
n
n
n
n
n
